# Generated by Django 3.1.5 on 2021-01-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('mbl', models.IntegerField()),
                ('mail_id', models.EmailField(max_length=30)),
                ('entry_date', models.DateField()),
            ],
            
        ),
    ]
